spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: v&C^DdeeaH7o5M$Y
  jpa:
    show-sql: true
server:
  port: 8081
staffjoy:
  email-service-endpoint: http://localhost:8088
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
